### ISSUE TITLE
Doesn't install

### ISSUE THREAD

**Issue by krebbi** [wardhache/community_store_reviews#1]
hi,

unfortunately i'm not able to install this Addon:

The class 'Concrete\Package\CommunityStore\Src\CommunityStore\Order\Order' was not found in the chain configured namespaces Concrete\Core\Entity, Concrete\Package\CommunityStoreReviews\Src

concrete version 8.1.0

any ideas?

cheers

**Comment by wardhache** [comment]
Hey Krebbi,

Seems like there was a problem with the linking to community store tables.
I fixed that issue and now it should install again.

Please let me know if any problems still occur, and I am sorry for the late response.

I hope you enjoy this package!

Cheers,
Ward
